### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by chankruze** [harshmangalam/hydrogen-solidjs-client#76]
```
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  lodash.debounce (imported by /home/chankruze/hydrogen-solidjs-client/src/components/header/Search.jsx)

Are they installed?
    at optimizeDeps (/home/chankruze/hydrogen-solidjs-client/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:56527:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOptimize (/home/chankruze/hydrogen-solidjs-client/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60549:48)
    at async Server.httpServer.listen (/home/chankruze/hydrogen-solidjs-client/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60565:21)
 ELIFECYCLE  Command failed with exit code 1.
 ```

Most probably happening after merging https://github.com/harshmangalam/hydrogen-solidjs-client/pull/72. @harshmangalam please have a look.

**Comment by harshmangalam** [comment]
This issues has been resolved you can take updated pull
